### ISSUE TITLE
WGSL variable is ignored by the mangler

### ISSUE THREAD

**Issue by ooflorent** [CodyJasonBennett/shaderkit#12]
The minifier is unable to identify some variables in WSGL.

The issue can already be observed by looking at the current snapshots where `output` is not mangled.

### Reproduction

```js
it('mangle WGSL variables', () => {
  const mangleMap = new Map()
  const shader = /* wgsl */ `@vertex fn main() -> void { var test: f32; }`
  expect(minify(shader, { mangle: true, mangleMap })).toMatchSnapshot()
  expect(mangleMap).toContain('test')
  //                ^^^^^^^^^ AssertionError: expected Map{} to include 'test'
})
```

**Comment by CodyJasonBennett** [comment]
I'd advise against using the mangler until I harden it with an AST ([shaderkit#ast](https://github.com/CodyJasonBennett/shaderkit/tree/ast)). #8 namely has me afraid for non-trivial shaders.

**Comment by CodyJasonBennett** [comment]
This looks to be skipped since `void` is not a valid keyword in WGSL and treated as an identifier. The behavior is still very wrong until I implement a proper AST (#14), but this should work with valid WGSL `fn main() { var test: f32; }`.

**Comment by CodyJasonBennett** [comment]
I've harden surrounding cases in the latest release. Let me know if this was somehow missed.
