### ISSUE TITLE
mangler charset  includes "`" character

### ISSUE THREAD

**Issue by dekdevy** [CodyJasonBennett/shaderkit#3]
When mangling, the "`" character will be used to generate mangled names, which breaks GLSL code.

Example manglemap snippet:
```
'PI' => 'x',
'facing' => 'y',
'lambertian' => 'a`',
'reflectDir' => 'aa',
'specular' => 'ab',
```

**Comment by CodyJasonBennett** [comment]
Is "`" being inserted by the mangler?

**Comment by dekdevy** [comment]
Looks like it, at mangleindex 26
```
String.fromCharCode(97 + ((26 % 26) - 1))
=> '`' 
```

I believe this would produce the desired outcome
```
for(let j = 0; j < 27; ++j) console.log(String.fromCharCode(97 + (j % 26)))
```
